version: "3.9"
services:
  bot:
    build: .
    ports:
      - "42069:42069"
    depends_on:
      - redis
      - postgres
    restart: always
  redis:
    image: "redis:alpine"
    restart: always
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_DB: bot
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: makelovenotwar
    volumes:
      - ./postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: "postgres"
    ports:
      - "8080:8080"
    profiles:
      - debug